name: Java+Maven CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  ci:
    uses: arbtemporg1/shared-workflows/.github/workflows/mvn-java.yml@master
    secrets: inherit
    with:
      java-version: 8
